# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wynik_1',
            name='set_1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wynik_1',
            name='set_2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wynik_1',
            name='set_3',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wynik_1',
            name='set_4',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wynik_2',
            name='set_1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wynik_2',
            name='set_2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wynik_2',
            name='set_3',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wynik_2',
            name='set_4',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='data_badania',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='nr_licencji',
            field=models.IntegerField(null=True),
        ),
    ]
