# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0002_auto_20170904_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TurniejWewnetrzny',
            new_name='PojedynekWewnetrzny',
        ),
    ]
