# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0003_auto_20170904_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wynik_1',
            name='zawodnik_1',
        ),
        migrations.RemoveField(
            model_name='wynik_2',
            name='zawodnik_2',
        ),
        migrations.RemoveField(
            model_name='pojedynekwewnetrzny',
            name='wynik_1',
        ),
        migrations.RemoveField(
            model_name='pojedynekwewnetrzny',
            name='wynik_2',
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='set_1_zaw_1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='set_1_zaw_2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='set_2_zaw_1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='set_2_zaw_2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='set_3_zaw_1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='set_3_zaw_2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='set_4_zaw_1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='set_4_zaw_2',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='zawodnik_1',
            field=models.ManyToManyField(related_name='zawodnik_1', to='tenisowka_app.Zawodnik'),
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='zawodnik_2',
            field=models.ManyToManyField(related_name='zawodnik_2', to='tenisowka_app.Zawodnik'),
        ),
        migrations.DeleteModel(
            name='Wynik_1',
        ),
        migrations.DeleteModel(
            name='Wynik_2',
        ),
    ]
