# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0004_auto_20170904_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojedynekwewnetrzny',
            name='data',
            field=models.DateField(),
        ),
    ]
