# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0005_auto_20170904_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='wynik_zaw_1',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pojedynekwewnetrzny',
            name='wynik_zaw_2',
            field=models.SmallIntegerField(null=True),
        ),
    ]
