# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0007_auto_20170904_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PojedynekWewnetrzny',
            new_name='Pojedynek',
        ),
    ]
