# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0008_auto_20170904_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pojedynek',
            name='zawodnik_1',
        ),
        migrations.AddField(
            model_name='pojedynek',
            name='zawodnik_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zawodnik_1', to='tenisowka_app.Zawodnik'),
        ),
        migrations.RemoveField(
            model_name='pojedynek',
            name='zawodnik_2',
        ),
        migrations.AddField(
            model_name='pojedynek',
            name='zawodnik_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zawodnik_2', to='tenisowka_app.Zawodnik'),
        ),
    ]
