# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-06 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0010_auto_20170906_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojedynek',
            name='set_1_zaw_1',
            field=models.SmallIntegerField(default=None),
        ),
    ]
