# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-17 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0012_auto_20170910_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('koniec', models.DateTimeField(blank=True, null=True)),
                ('typ', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
