# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-17 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0013_wydarzenie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pojedynek',
            options={'verbose_name': 'Pojedynek', 'verbose_name_plural': 'Pojedynki'},
        ),
        migrations.AlterModelOptions(
            name='wydarzenie',
            options={'verbose_name': 'Wydarzenie', 'verbose_name_plural': 'Wydarzenia'},
        ),
        migrations.AlterModelOptions(
            name='zawodnik',
            options={'verbose_name': 'Zawodnik', 'verbose_name_plural': 'Zawodnicy'},
        ),
        migrations.RemoveField(
            model_name='wydarzenie',
            name='typ',
        ),
    ]
