# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0014_auto_20170917_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='zawodnik',
            name='data_urodzenia',
            field=models.DateField(null=True),
        ),
    ]
