# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-21 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0015_zawodnik_data_urodzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydarzenie',
            name='opis',
            field=models.TextField(null=True),
        ),
    ]
