# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0016_wydarzenie_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydarzenie',
            name='koniec',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='nazwa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
