# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-27 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0017_auto_20170926_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zawodnik',
            name='adres',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='zawodnik',
            name='data_badania',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zawodnik',
            name='data_urodzenia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zawodnik',
            name='nr_licencji',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
