# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-28 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0020_auto_20170928_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='result_pl_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result_pl_2',
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_result',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='wynik zawodnika 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_result',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='wynik zawodnika 2'),
        ),
    ]
