# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-28 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0021_auto_20170928_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_1_result',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='wynik zawodnika 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_result',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='wynik zawodnika 2'),
        ),
    ]
