# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-28 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0023_auto_20170928_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
    ]
