# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-30 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0024_match_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenisowka_app.Event', verbose_name='Wydarzenie')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenisowka_app.Player', verbose_name='Zawodnik')),
            ],
        ),
    ]
