# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-30 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenisowka_app', '0027_auto_20170930_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='player',
            new_name='players',
        ),
    ]
